// Mock Data representing live Wagr.io database collections

export const mockMarkets = [
  {
    _id: 'm1',
    title: 'Will OpenAI announce GPT-6 before December 2026?',
    description: 'Resolves to YES if OpenAI officially announces or releases the GPT-6 large language model before December 31, 2026, 23:59 UTC. Otherwise, resolves to NO.',
    category: 'Artificial Intelligence',
    yesProbability: 68,
    noProbability: 32,
    volume: 125400,
    participants: 412,
    status: 'Live',
    resolutionDate: '2026-12-31T23:59:59.000Z',
    createdBy: 'admin1',
    createdAt: '2026-07-01T12:00:00.000Z',
  },
  {
    _id: 'm2',
    title: 'Will SpaceX launch Starship Flight 6 in Q3 2026?',
    description: 'Resolves to YES if SpaceX successfully launches the Starship Flight 6 test vehicle between July 1, 2026, and September 30, 2026, 23:59 UTC. Otherwise, resolves to NO.',
    category: 'Technology',
    yesProbability: 74,
    noProbability: 26,
    volume: 84300,
    participants: 289,
    status: 'Live',
    resolutionDate: '2026-09-30T23:59:59.000Z',
    createdBy: 'admin1',
    createdAt: '2026-07-02T10:00:00.000Z',
  },
  {
    _id: 'm3',
    title: 'Will the Fed cut interest rates in their September 2026 meeting?',
    description: 'Resolves to YES if the Federal Reserve officially announces a decrease in the federal funds rate at their September 2026 policy meeting. Otherwise, resolves to NO.',
    category: 'Finance',
    yesProbability: 43,
    noProbability: 57,
    volume: 184000,
    participants: 624,
    status: 'Live',
    resolutionDate: '2026-09-18T18:00:00.000Z',
    createdBy: 'admin1',
    createdAt: '2026-07-03T09:00:00.000Z',
  },
  {
    _id: 'm4',
    title: 'Will Apple release a foldable iPhone in 2026?',
    description: 'Resolves to YES if Apple officially announces or releases a commercial iPhone featuring a folding display before December 31, 2026, 23:59 UTC. Otherwise, resolves to NO.',
    category: 'Technology',
    yesProbability: 35,
    noProbability: 65,
    volume: 67200,
    participants: 198,
    status: 'Live',
    resolutionDate: '2026-12-31T23:59:59.000Z',
    createdBy: 'admin1',
    createdAt: '2026-07-04T15:00:00.000Z',
  },
  {
    _id: 'm5',
    title: 'Will Anthropic Claude 4 outperform GPT-6 on MMLU?',
    description: 'Resolves to YES if Anthropic officially releases Claude 4 and its reported MMLU benchmark score is higher than that of OpenAI GPT-6, as verified by official technical reports before the end of 2026. Otherwise, resolves to NO.',
    category: 'Artificial Intelligence',
    yesProbability: 52,
    noProbability: 48,
    volume: 98100,
    participants: 345,
    status: 'Live',
    resolutionDate: '2026-12-31T23:59:59.000Z',
    createdBy: 'admin1',
    createdAt: '2026-07-05T08:00:00.000Z',
  },
];

export const mockNews = [
  {
    _id: 'n1',
    headline: 'OpenAI CEO hints at next-generation model release window',
    summary: 'In a recent interview, Sam Altman suggested that their next major model, GPT-5, is currently undergoing extensive red-teaming and could see a release late this year or early next year.',
    source: 'TechCrunch',
    url: 'https://techcrunch.com/openai-gpt5-hints',
    category: 'Artificial Intelligence',
    relatedMarket: 'm1',
    publishedDate: '2026-07-05T14:30:00.000Z',
    aiSummary: 'OpenAI CEO signals model completion and safety reviews, raising expectations for an announcement within the next few months.',
  },
  {
    _id: 'n2',
    headline: 'Federal Reserve Chairman speaks on inflation and rate trajectories',
    summary: 'The Federal Reserve signaled that inflation rates are approaching target corridors, keeping option doors open for a potential quarter-point cut at the upcoming September committee conference.',
    source: 'Bloomberg',
    url: 'https://bloomberg.com/fed-september-interest',
    category: 'Finance',
    relatedMarket: 'm3',
    publishedDate: '2026-07-04T11:15:00.000Z',
    aiSummary: 'Fed leaves doors open for rate reductions in Q3, shifting probabilities for macroeconomic prediction contracts.',
  },
  {
    _id: 'n3',
    headline: 'SpaceX completes hot-fire test for next Starship vehicle',
    summary: 'SpaceX technicians successfully completed a static fire of Ship 31, preparing the booster and ship elements for Flight 6, tentatively scheduled for late Q3.',
    source: 'SpaceFlight Now',
    url: 'https://spaceflightnow.com/spacex-starship-flight6-test',
    category: 'Technology',
    relatedMarket: 'm2',
    publishedDate: '2026-07-03T18:45:00.000Z',
    aiSummary: 'SpaceX accelerates Starship Flight 6 launch preparations, reinforcing predictions of a Q3 launch timeline.',
  },
];

export const mockPosts = [
  {
    _id: 'p1',
    userId: {
      fullName: 'Apurv Khairnar',
      username: 'apurv',
    },
    content: 'OpenAI has been pushing safety updates aggressively. I think GPT-5 red-teaming might wrap up faster than expected. Betting YES on the GPT-5 announcement before December.',
    linkedMarket: 'm1',
    likesCount: 24,
    commentsCount: 8,
    createdAt: '2026-07-05T16:20:00.000Z',
  },
  {
    _id: 'p2',
    userId: {
      fullName: 'Forecaster Pro',
      username: 'predict_win',
    },
    content: 'Macroeconomic indicators show CPI index easing. The Fed will cut rates by 25bps in September to stabilize employment. The NO odds at 57% are a huge mispricing!',
    linkedMarket: 'm3',
    likesCount: 18,
    commentsCount: 12,
    createdAt: '2026-07-04T09:40:00.000Z',
  },
  {
    _id: 'p3',
    userId: {
      fullName: 'Space Nerd',
      username: 'starship_fan',
    },
    content: 'Starship flight 5 was an absolute success with the booster catch. Flight 6 has minor upgrades, and launch licensing should clear quickly. Q3 launch is almost guaranteed!',
    linkedMarket: 'm2',
    likesCount: 31,
    commentsCount: 5,
    createdAt: '2026-07-03T20:10:00.000Z',
  },
];
